# Generated by Django 4.2.30 on 2026-08-25 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('families', '0001_initial'),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='household',
            name='head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_households', to='members.person'),
        ),
        migrations.AddField(
            model_name='household',
            name='spouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spouse_households', to='members.person'),
        ),
        migrations.AddField(
            model_name='familybranch',
            name='current_leader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_branches', to='members.person'),
        ),
        migrations.AddField(
            model_name='familybranch',
            name='founder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='founded_branches', to='members.person'),
        ),
    ]
