# Generated by Django 4.2.30 on 2026-09-22 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("families", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClanIdentity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("clan_name", models.CharField(default="Moshi", max_length=100)),
            ],
        ),
    ]
