# Generated by Django 4.2.30 on 2026-08-25 13:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('families', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('document_type', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(upload_to='documents/')),
                ('access_level', models.CharField(choices=[('public', 'Public'), ('members', 'Clan members only'), ('restricted', 'Restricted'), ('admin', 'Administrator only')], default='restricted', max_length=16)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('related_branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='families.familybranch')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('event_type', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('date', models.DateField()),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('organizer', models.CharField(blank=True, max_length=150)),
                ('contact_person', models.CharField(blank=True, max_length=150)),
                ('access_level', models.CharField(choices=[('public', 'Public'), ('members', 'Clan members only'), ('restricted', 'Restricted'), ('admin', 'Administrator only')], default='members', max_length=16)),
            ],
            options={
                'ordering': ['-date', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_id', models.CharField(max_length=40, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('clan_name', models.CharField(default='Moshi', max_length=100)),
                ('gender', models.CharField(choices=[('female', 'Female'), ('male', 'Male'), ('other', 'Other'), ('unknown', 'Unknown')], default='unknown', max_length=16)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('place_of_birth', models.CharField(blank=True, max_length=255)),
                ('nationality', models.CharField(blank=True, max_length=100)),
                ('current_residence', models.CharField(blank=True, max_length=255)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('occupation', models.CharField(blank=True, max_length=150)),
                ('education', models.CharField(blank=True, max_length=255)),
                ('phone_number', models.CharField(blank=True, max_length=32)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='members/photos/')),
                ('biography', models.TextField(blank=True)),
                ('is_living', models.BooleanField(default=True)),
                ('date_of_death', models.DateField(blank=True, null=True)),
                ('place_of_death', models.CharField(blank=True, max_length=255)),
                ('burial_location', models.CharField(blank=True, max_length=255)),
                ('memorial_information', models.TextField(blank=True)),
                ('generation', models.PositiveIntegerField(blank=True, null=True)),
                ('relationship_to_founder', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('pending_verification', 'Pending verification'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('archived', 'Archived')], default='draft', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='person_profile', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_people', to=settings.AUTH_USER_MODEL)),
                ('family_branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='families.familybranch')),
                ('father', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fathered_children', to='members.person')),
                ('household', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='families.household')),
                ('mother', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mothered_children', to='members.person')),
            ],
            options={
                'ordering': ['last_name', 'first_name', 'member_id'],
            },
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_type', models.CharField(choices=[('father', 'Father'), ('mother', 'Mother'), ('parent', 'Parent'), ('child', 'Child'), ('husband', 'Husband'), ('wife', 'Wife'), ('spouse', 'Spouse'), ('brother', 'Brother'), ('sister', 'Sister'), ('sibling', 'Sibling'), ('grandparent', 'Grandparent'), ('grandchild', 'Grandchild'), ('guardian', 'Guardian'), ('adopted_child', 'Adopted child')], max_length=32)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('pending_verification', 'Pending verification'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('archived', 'Archived')], default='pending_verification', max_length=32)),
                ('notes', models.TextField(blank=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_from', to='members.person')),
                ('to_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_to', to='members.person')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_relationships', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('channel', models.CharField(default='in_app', max_length=50)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('media_type', models.CharField(choices=[('photo', 'Photo'), ('video', 'Video'), ('audio', 'Audio')], default='photo', max_length=16)),
                ('file', models.FileField(upload_to='media_gallery/')),
                ('description', models.TextField(blank=True)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('access_level', models.CharField(choices=[('public', 'Public'), ('members', 'Clan members only'), ('restricted', 'Restricted'), ('admin', 'Administrator only')], default='members', max_length=16)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.event')),
                ('related_branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='families.familybranch')),
                ('related_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.person')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'media',
            },
        ),
        migrations.CreateModel(
            name='Marriage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('pending_verification', 'Pending verification'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('archived', 'Archived')], default='pending_verification', max_length=32)),
                ('notes', models.TextField(blank=True)),
                ('spouse_one', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marriages_as_spouse_one', to='members.person')),
                ('spouse_two', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marriages_as_spouse_two', to='members.person')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='events', to='members.person'),
        ),
        migrations.AddField(
            model_name='event',
            name='related_documents',
            field=models.ManyToManyField(blank=True, related_name='events', to='members.document'),
        ),
        migrations.AddField(
            model_name='document',
            name='related_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.person'),
        ),
        migrations.AddField(
            model_name='document',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='CorrectionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100)),
                ('current_value', models.TextField(blank=True)),
                ('proposed_value', models.TextField()),
                ('reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('pending_verification', 'Pending verification'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('archived', 'Archived')], default='submitted', max_length=32)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correction_requests', to='members.person')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_corrections', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClanHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('access_level', models.CharField(choices=[('public', 'Public'), ('members', 'Clan members only'), ('restricted', 'Restricted'), ('admin', 'Administrator only')], default='public', max_length=16)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('pending_verification', 'Pending verification'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('archived', 'Archived')], default='draft', max_length=32)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'clan histories',
            },
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('audience', models.CharField(choices=[('entire_clan', 'Entire clan'), ('family_branch', 'Family branch'), ('administrators', 'Administrators'), ('selected_members', 'Selected members')], default='entire_clan', max_length=32)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('access_level', models.CharField(choices=[('public', 'Public'), ('members', 'Clan members only'), ('restricted', 'Restricted'), ('admin', 'Administrator only')], default='members', max_length=16)),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('selected_members', models.ManyToManyField(blank=True, related_name='targeted_announcements', to='members.person')),
                ('target_branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='families.familybranch')),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='relationship',
            constraint=models.UniqueConstraint(fields=('from_person', 'to_person', 'relationship_type'), name='unique_relationship_type_between_people'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['member_id'], name='members_per_member__5486fd_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['last_name', 'first_name'], name='members_per_last_na_51a326_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['family_branch', 'generation'], name='members_per_family__6dbfe0_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['is_living'], name='members_per_is_livi_c18f42_idx'),
        ),
    ]
