# Generated by Django 4.2.30 on 2026-09-22 05:15

from django.db import migrations, models
import families.identity


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0001_initial"),
        ("families", "0003_clanidentity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="clan_name",
            field=models.CharField(default=families.identity.clan_name, max_length=100),
        ),
        migrations.AlterField(
            model_name="person",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("female", "Female"), ("male", "Male")],
                max_length=16,
            ),
        ),
    ]
